export const ACTION_POST_MESSAGE = {
    FPR_LIST_WORD: "FPR_LIST_WORD",
    FPR_HEIGHT: "FPR_HEIGHT",
    FPR_RESP_DATA: "FPR_RESP_DATA",
    FPR_NAVIGATE: "NAVIGATE",
    FPR_SUBMIT_GRADING: "FPR_SUBMIT_GRADING",
    FPR_SUBMIT_AUDIO_ASSESSMENT: "FPR_SUBMIT_AUDIO_ASSESSMENT",
} as const;
