export const ACTION_POST_MESSAGE = {
    FPR_LIST_WORD: "FPR_LIST_WORD",
    FPR_HEIGHT: "FPR_HEIGHT",
    FPR_RESP_DATA: "FPR_RESP_DATA",
    FPR_NAVIGATE: "NAVIGATE",
    FPR_SUBMIT_GRADING: "FPR_SUBMIT_GRADING",
    FPR_SUBMIT_AUDIO_ASSESSMENT: "FPR_SUBMIT_AUDIO_ASSESSMENT",
    FPR_GET_SYNC_AUDIO: "FPR_GET_SYNC_AUDIO",
    FPR_RESP_SYNC_AUDIO: "FPR_RESP_SYNC_AUDIO",
    FPR_GRADE_VALIDATE: "FPR_GRADE_VALIDATE",
    FPR_CHANGE_STUDENT: "FPR_CHANGE_STUDENT",
} as const;
