export const OPTIONS_SURVEY = {
    LEVEL_ONE: {
        SELF_GUIDED: 'SELF_GUIDED_ASSESSMENT',
        TEACHER_ADMINISTER: 'TEACHER_ADMINISTERED_ASSESSMENT',
    },
    LEVEL_TWO: {
        WITH_RECORD: 'TEACHER_ADMINISTERED_ASSESSMENT_WITH_RECORDING',
        WITHOUT_RECORD: 'TEACHER_ADMINISTERED_ASSESSMENT_WITHOUT_RECORDING',
    },
} as const;
