export const ACTION_POST_MESSAGE = {
    FPR_LIST_WORD: "LIST_WORD",
    FPR_HEIGHT: "HEIGHT",
    FPR_GET_AUDIO: "FPR_GET_AUDIO",
    FPR_SEND_AUDIO: "FPR_SEND_AUDIO",
    FPR_RESP_DATA: "RESP_DATA",
    FPR_NAVIGATE: "NAVIGATE",
    FPR_SUBMIT_GRADING: "SUBMIT_GRADING",
} as const;
